/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "S3-Store eCommerce Platform",
  "tagline": "Guides and API Docs",
  "favicon": "img/favicon.ico",
  "url": "https://s3-store.org",
  "baseUrl": "/",
  "organizationName": "S3_STORE",
  "projectName": "S3_Store",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "future": {
    "experimental_faster": {
      "swcJsLoader": true,
      "swcJsMinimizer": true,
      "swcHtmlMinimizer": true,
      "lightningCssMinimizer": true,
      "mdxCrossCompilerCache": true,
      "rspackBundler": true
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.js",
          "editUrl": "https://github.com/S3-Store/s3_guide/tree/main",
          "docItemComponent": "@theme/ApiItem"
        },
        "blog": false,
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/docusaurus-social-card.jpg",
    "navbar": {
      "title": "S3-Store",
      "logo": {
        "alt": "S3-Store Logo",
        "src": "img/logo.svg"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "tutorialSidebar",
          "position": "left",
          "label": "Tutorial"
        },
        {
          "to": "/blog",
          "label": "Blog",
          "position": "left"
        },
        {
          "label": "Petstore API",
          "position": "left",
          "to": "/docs/category/petstore-versioned-api"
        },
        {
          "href": "https://github.com/S3-Store/s3_store",
          "position": "right",
          "className": "header-github-link",
          "aria-label": "GitHub repository"
        }
      ],
      "hideOnScroll": false
    },
    "docs": {
      "sidebar": {
        "autoCollapseCategories": true,
        "hideable": true
      },
      "versionPersistence": "localStorage"
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Tutorial",
              "to": "/docs/intro"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Stack Overflow",
              "href": "https://stackoverflow.com/questions/tagged/docusaurus"
            },
            {
              "label": "Discord",
              "href": "https://discordapp.com/invite/docusaurus"
            },
            {
              "label": "X",
              "href": "https://x.com/docusaurus"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "Blog",
              "to": "/blog"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/S3-Store/"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2025 GMS, Template provided by Docusaurus Tailwind Shadcn. Templates by <a href=\"https://github.com/namnguyenthanhwork\" style=\"font-weight: bold;\" target=\"_blank\">Thành Nam Nguyễn</a>"
    },
    "prism": {
      "additionalLanguages": [
        "ruby",
        "csharp",
        "php",
        "java",
        "powershell",
        "json",
        "bash",
        "dart",
        "objectivec",
        "r"
      ],
      "theme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "languageTabs": [
      {
        "highlight": "python",
        "language": "python",
        "logoClass": "python"
      },
      {
        "highlight": "bash",
        "language": "curl",
        "logoClass": "curl"
      },
      {
        "highlight": "csharp",
        "language": "csharp",
        "logoClass": "csharp"
      },
      {
        "highlight": "go",
        "language": "go",
        "logoClass": "go"
      },
      {
        "highlight": "javascript",
        "language": "nodejs",
        "logoClass": "nodejs"
      },
      {
        "highlight": "ruby",
        "language": "ruby",
        "logoClass": "ruby"
      },
      {
        "highlight": "php",
        "language": "php",
        "logoClass": "php"
      },
      {
        "highlight": "java",
        "language": "java",
        "logoClass": "java",
        "variant": "unirest"
      },
      {
        "highlight": "powershell",
        "language": "powershell",
        "logoClass": "powershell"
      },
      {
        "highlight": "dart",
        "language": "dart",
        "logoClass": "dart"
      },
      {
        "highlight": "javascript",
        "language": "javascript",
        "logoClass": "javascript"
      },
      {
        "highlight": "c",
        "language": "c",
        "logoClass": "c"
      },
      {
        "highlight": "objective-c",
        "language": "objective-c",
        "logoClass": "objective-c"
      },
      {
        "highlight": "ocaml",
        "language": "ocaml",
        "logoClass": "ocaml"
      },
      {
        "highlight": "r",
        "language": "r",
        "logoClass": "r"
      },
      {
        "highlight": "swift",
        "language": "swift",
        "logoClass": "swift"
      },
      {
        "highlight": "kotlin",
        "language": "kotlin",
        "logoClass": "kotlin"
      },
      {
        "highlight": "rust",
        "language": "rust",
        "logoClass": "rust"
      }
    ],
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "themes": [
    [
      "/Users/fthobe/Repositories/s3_guide/node_modules/@easyops-cn/docusaurus-search-local/dist/server/server/index.js",
      {
        "indexPages": true,
        "docsRouteBasePath": "/docs",
        "hashed": true,
        "language": [
          "en"
        ],
        "highlightSearchTermsOnTargetPage": false,
        "searchResultContextMaxLength": 50,
        "searchResultLimits": 8,
        "searchBarShortcut": true,
        "searchBarShortcutHint": true
      }
    ],
    "docusaurus-theme-openapi-docs"
  ],
  "plugins": [
    [
      "./src/plugins/tailwind-config.js",
      {}
    ],
    [
      "docusaurus-plugin-openapi-docs",
      {
        "id": "openapi",
        "docsPluginId": "classic",
        "config": {
          "petstore_versioned": {
            "specPath": "api-swagger/petstore.yaml",
            "outputDir": "docs/petstore_versioned",
            "sidebarOptions": {
              "groupPathsBy": "tag",
              "categoryLinkSource": "tag"
            },
            "version": "2.0.0",
            "label": "v2.0.0",
            "baseUrl": "/docs/petstore_versioned/swagger-petstore-yaml",
            "downloadUrl": "https://raw.githubusercontent.com/namnguyenthanhwork/docusaurus-tailwind-shadcn-template/main/api-swagger/petstore.yaml",
            "versions": {
              "1.0.0": {
                "specPath": "api-swagger/petstore-1.0.0.yaml",
                "outputDir": "docs/petstore_versioned/1.0.0",
                "label": "v1.0.0",
                "baseUrl": "/docs/petstore_versioned/1.0.0/swagger-petstore-yaml",
                "downloadUrl": "https://raw.githubusercontent.com/namnguyenthanhwork/docusaurus-tailwind-shadcn-template/main/api-swagger/petstore-1.0.0.yaml"
              }
            }
          }
        }
      }
    ],
    [
      "ideal-image",
      {
        "quality": 70,
        "max": 1030,
        "min": 640,
        "steps": 2,
        "disableInDev": true
      }
    ],
    [
      "./src/plugins/blog-plugin",
      {
        "path": "blog",
        "editLocalizedFiles": false,
        "blogTitle": "Blog",
        "blogDescription": "Blog description is here ...",
        "blogSidebarCount": "ALL",
        "blogSidebarTitle": "List blog",
        "routeBasePath": "blog",
        "include": [
          "**/*.md",
          "**/*.mdx"
        ],
        "exclude": [
          "**/_*.{js,jsx,ts,tsx,md,mdx}",
          "**/_*/**",
          "**/*.test.{js,jsx,ts,tsx}",
          "**/__tests__/**"
        ],
        "postsPerPage": 6,
        "truncateMarker": {},
        "showReadingTime": true,
        "onUntruncatedBlogPosts": "ignore",
        "editUrl": "https://github.com/namnguyenthanhwork/docusaurus-tailwind-shadcn-template/tree/main/",
        "remarkPlugins": [
          [
            null,
            {
              "sync": true
            }
          ]
        ]
      }
    ]
  ],
  "baseUrlIssueBanner": true,
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  }
};
